// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/trip.proto

package trip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageSlug int32

const (
	PackageSlug_PACKAGE_SLUG_UNSPECIFIED PackageSlug = 0
	PackageSlug_UBERX                    PackageSlug = 1
	PackageSlug_BLACK                    PackageSlug = 2
)

// Enum value maps for PackageSlug.
var (
	PackageSlug_name = map[int32]string{
		0: "PACKAGE_SLUG_UNSPECIFIED",
		1: "UBERX",
		2: "BLACK",
	}
	PackageSlug_value = map[string]int32{
		"PACKAGE_SLUG_UNSPECIFIED": 0,
		"UBERX":                    1,
		"BLACK":                    2,
	}
)

func (x PackageSlug) Enum() *PackageSlug {
	p := new(PackageSlug)
	*p = x
	return p
}

func (x PackageSlug) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageSlug) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_trip_proto_enumTypes[0].Descriptor()
}

func (PackageSlug) Type() protoreflect.EnumType {
	return &file_proto_trip_proto_enumTypes[0]
}

func (x PackageSlug) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageSlug.Descriptor instead.
func (PackageSlug) EnumDescriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{0}
}

type PreviewTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerID   string                 `protobuf:"bytes,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	StartLocation *Coordinate            `protobuf:"bytes,2,opt,name=startLocation,proto3" json:"startLocation,omitempty"`
	EndLocation   *Coordinate            `protobuf:"bytes,3,opt,name=endLocation,proto3" json:"endLocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripRequest) Reset() {
	*x = PreviewTripRequest{}
	mi := &file_proto_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripRequest) ProtoMessage() {}

func (x *PreviewTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripRequest.ProtoReflect.Descriptor instead.
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewTripRequest) GetPassengerID() string {
	if x != nil {
		return x.PassengerID
	}
	return ""
}

func (x *PreviewTripRequest) GetStartLocation() *Coordinate {
	if x != nil {
		return x.StartLocation
	}
	return nil
}

func (x *PreviewTripRequest) GetEndLocation() *Coordinate {
	if x != nil {
		return x.EndLocation
	}
	return nil
}

type PreviewTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=tripId,proto3" json:"tripId,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	RideFares     []*RideFare            `protobuf:"bytes,3,rep,name=rideFares,proto3" json:"rideFares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripResponse) Reset() {
	*x = PreviewTripResponse{}
	mi := &file_proto_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripResponse) ProtoMessage() {}

func (x *PreviewTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripResponse.ProtoReflect.Descriptor instead.
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *PreviewTripResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *PreviewTripResponse) GetRideFares() []*RideFare {
	if x != nil {
		return x.RideFares
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_proto_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{2}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Geometry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Coordinate          `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_proto_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{3}
}

func (x *Geometry) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geometry      []*Geometry            `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{4}
}

func (x *Route) GetGeometry() []*Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Route) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Route) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type RideFare struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PassengerID       string                 `protobuf:"bytes,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	PackageSlug       PackageSlug            `protobuf:"varint,3,opt,name=packageSlug,proto3,enum=trip.PackageSlug" json:"packageSlug,omitempty"`
	TotalPriceInCents float64                `protobuf:"fixed64,4,opt,name=totalPriceInCents,proto3" json:"totalPriceInCents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RideFare) Reset() {
	*x = RideFare{}
	mi := &file_proto_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideFare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideFare) ProtoMessage() {}

func (x *RideFare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideFare.ProtoReflect.Descriptor instead.
func (*RideFare) Descriptor() ([]byte, []int) {
	return file_proto_trip_proto_rawDescGZIP(), []int{5}
}

func (x *RideFare) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RideFare) GetPassengerID() string {
	if x != nil {
		return x.PassengerID
	}
	return ""
}

func (x *RideFare) GetPackageSlug() PackageSlug {
	if x != nil {
		return x.PackageSlug
	}
	return PackageSlug_PACKAGE_SLUG_UNSPECIFIED
}

func (x *RideFare) GetTotalPriceInCents() float64 {
	if x != nil {
		return x.TotalPriceInCents
	}
	return 0
}

var File_proto_trip_proto protoreflect.FileDescriptor

const file_proto_trip_proto_rawDesc = "" +
	"\n" +
	"\x10proto/trip.proto\x12\x04trip\"\xa2\x01\n" +
	"\x12PreviewTripRequest\x12 \n" +
	"\vpassengerID\x18\x01 \x01(\tR\vpassengerID\x126\n" +
	"\rstartLocation\x18\x02 \x01(\v2\x10.trip.CoordinateR\rstartLocation\x122\n" +
	"\vendLocation\x18\x03 \x01(\v2\x10.trip.CoordinateR\vendLocation\"~\n" +
	"\x13PreviewTripResponse\x12\x16\n" +
	"\x06tripId\x18\x01 \x01(\tR\x06tripId\x12!\n" +
	"\x05route\x18\x02 \x01(\v2\v.trip.RouteR\x05route\x12,\n" +
	"\trideFares\x18\x03 \x03(\v2\x0e.trip.RideFareR\trideFares\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\">\n" +
	"\bGeometry\x122\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x10.trip.CoordinateR\vcoordinates\"k\n" +
	"\x05Route\x12*\n" +
	"\bgeometry\x18\x01 \x03(\v2\x0e.trip.GeometryR\bgeometry\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\"\x9f\x01\n" +
	"\bRideFare\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vpassengerID\x18\x02 \x01(\tR\vpassengerID\x123\n" +
	"\vpackageSlug\x18\x03 \x01(\x0e2\x11.trip.PackageSlugR\vpackageSlug\x12,\n" +
	"\x11totalPriceInCents\x18\x04 \x01(\x01R\x11totalPriceInCents*A\n" +
	"\vPackageSlug\x12\x1c\n" +
	"\x18PACKAGE_SLUG_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05UBERX\x10\x01\x12\t\n" +
	"\x05BLACK\x10\x022Q\n" +
	"\vTripService\x12B\n" +
	"\vPreviewTrip\x12\x18.trip.PreviewTripRequest\x1a\x19.trip.PreviewTripResponseB\x18Z\x16shared/proto/trip;tripb\x06proto3"

var (
	file_proto_trip_proto_rawDescOnce sync.Once
	file_proto_trip_proto_rawDescData []byte
)

func file_proto_trip_proto_rawDescGZIP() []byte {
	file_proto_trip_proto_rawDescOnce.Do(func() {
		file_proto_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_proto_rawDesc), len(file_proto_trip_proto_rawDesc)))
	})
	return file_proto_trip_proto_rawDescData
}

var file_proto_trip_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_trip_proto_goTypes = []any{
	(PackageSlug)(0),            // 0: trip.PackageSlug
	(*PreviewTripRequest)(nil),  // 1: trip.PreviewTripRequest
	(*PreviewTripResponse)(nil), // 2: trip.PreviewTripResponse
	(*Coordinate)(nil),          // 3: trip.Coordinate
	(*Geometry)(nil),            // 4: trip.Geometry
	(*Route)(nil),               // 5: trip.Route
	(*RideFare)(nil),            // 6: trip.RideFare
}
var file_proto_trip_proto_depIdxs = []int32{
	3, // 0: trip.PreviewTripRequest.startLocation:type_name -> trip.Coordinate
	3, // 1: trip.PreviewTripRequest.endLocation:type_name -> trip.Coordinate
	5, // 2: trip.PreviewTripResponse.route:type_name -> trip.Route
	6, // 3: trip.PreviewTripResponse.rideFares:type_name -> trip.RideFare
	3, // 4: trip.Geometry.coordinates:type_name -> trip.Coordinate
	4, // 5: trip.Route.geometry:type_name -> trip.Geometry
	0, // 6: trip.RideFare.packageSlug:type_name -> trip.PackageSlug
	1, // 7: trip.TripService.PreviewTrip:input_type -> trip.PreviewTripRequest
	2, // 8: trip.TripService.PreviewTrip:output_type -> trip.PreviewTripResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_trip_proto_init() }
func file_proto_trip_proto_init() {
	if File_proto_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_proto_rawDesc), len(file_proto_trip_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trip_proto_goTypes,
		DependencyIndexes: file_proto_trip_proto_depIdxs,
		EnumInfos:         file_proto_trip_proto_enumTypes,
		MessageInfos:      file_proto_trip_proto_msgTypes,
	}.Build()
	File_proto_trip_proto = out.File
	file_proto_trip_proto_goTypes = nil
	file_proto_trip_proto_depIdxs = nil
}
