// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverStatusType int32

const (
	DriverStatusType_STATUS_TYPE_UNSPECIFIED DriverStatusType = 0
	DriverStatusType_ONLINE                  DriverStatusType = 1
	DriverStatusType_OFFLINE                 DriverStatusType = 2
)

// Enum value maps for DriverStatusType.
var (
	DriverStatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "ONLINE",
		2: "OFFLINE",
	}
	DriverStatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"ONLINE":                  1,
		"OFFLINE":                 2,
	}
)

func (x DriverStatusType) Enum() *DriverStatusType {
	p := new(DriverStatusType)
	*p = x
	return p
}

func (x DriverStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_driver_proto_enumTypes[0].Descriptor()
}

func (DriverStatusType) Type() protoreflect.EnumType {
	return &file_proto_driver_proto_enumTypes[0]
}

func (x DriverStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatusType.Descriptor instead.
func (DriverStatusType) EnumDescriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{0}
}

type UpdateStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverID       string                 `protobuf:"bytes,1,opt,name=DriverID,proto3" json:"DriverID,omitempty"`
	Status         DriverStatusType       `protobuf:"varint,2,opt,name=Status,proto3,enum=driver.DriverStatusType" json:"Status,omitempty"`
	ActualLocation *Coordinate            `protobuf:"bytes,3,opt,name=ActualLocation,proto3" json:"ActualLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStatusRequest) GetDriverID() string {
	if x != nil {
		return x.DriverID
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() DriverStatusType {
	if x != nil {
		return x.Status
	}
	return DriverStatusType_STATUS_TYPE_UNSPECIFIED
}

func (x *UpdateStatusRequest) GetActualLocation() *Coordinate {
	if x != nil {
		return x.ActualLocation
	}
	return nil
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_proto_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_proto_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{2}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_proto_driver_proto protoreflect.FileDescriptor

const file_proto_driver_proto_rawDesc = "" +
	"\n" +
	"\x12proto/driver.proto\x12\x06driver\"\x9f\x01\n" +
	"\x13UpdateStatusRequest\x12\x1a\n" +
	"\bDriverID\x18\x01 \x01(\tR\bDriverID\x120\n" +
	"\x06Status\x18\x02 \x01(\x0e2\x18.driver.DriverStatusTypeR\x06Status\x12:\n" +
	"\x0eActualLocation\x18\x03 \x01(\v2\x12.driver.CoordinateR\x0eActualLocation\"0\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude*H\n" +
	"\x10DriverStatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\v\n" +
	"\aOFFLINE\x10\x022Z\n" +
	"\rDriverService\x12I\n" +
	"\fUpdateStatus\x12\x1b.driver.UpdateStatusRequest\x1a\x1c.driver.UpdateStatusResponseB\x1cZ\x1ashared/proto/driver;driverb\x06proto3"

var (
	file_proto_driver_proto_rawDescOnce sync.Once
	file_proto_driver_proto_rawDescData []byte
)

func file_proto_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_proto_rawDesc), len(file_proto_driver_proto_rawDesc)))
	})
	return file_proto_driver_proto_rawDescData
}

var file_proto_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_driver_proto_goTypes = []any{
	(DriverStatusType)(0),        // 0: driver.DriverStatusType
	(*UpdateStatusRequest)(nil),  // 1: driver.UpdateStatusRequest
	(*UpdateStatusResponse)(nil), // 2: driver.UpdateStatusResponse
	(*Coordinate)(nil),           // 3: driver.Coordinate
}
var file_proto_driver_proto_depIdxs = []int32{
	0, // 0: driver.UpdateStatusRequest.Status:type_name -> driver.DriverStatusType
	3, // 1: driver.UpdateStatusRequest.ActualLocation:type_name -> driver.Coordinate
	1, // 2: driver.DriverService.UpdateStatus:input_type -> driver.UpdateStatusRequest
	2, // 3: driver.DriverService.UpdateStatus:output_type -> driver.UpdateStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_driver_proto_init() }
func file_proto_driver_proto_init() {
	if File_proto_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_proto_rawDesc), len(file_proto_driver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_proto_depIdxs,
		EnumInfos:         file_proto_driver_proto_enumTypes,
		MessageInfos:      file_proto_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_proto = out.File
	file_proto_driver_proto_goTypes = nil
	file_proto_driver_proto_depIdxs = nil
}
